### ISSUE TITLE
Could not initialize class com.github.intelliguard.ui.JarOptionsForm

### ISSUE THREAD

**Issue by ghost** [ronniekk/intelliguard#1]

**Comment by ghost** [comment]
Could not initialize class com.github.intelliguard.ui.JarOptionsForm: Could not initialize class com.github.intelliguard.ui.JarOptionsForm
java.lang.NoClassDefFoundError: Could not initialize class com.github.intelliguard.ui.JarOptionsForm
    at com.github.intelliguard.ui.FormDialogWrapper.showJarOptionsForm(FormDialogWrapper.java:36)
    at com.github.intelliguard.action.RunObfuscationAction.actionPerformed(RunObfuscationAction.java:108)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:261)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:916)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:231)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:104)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by rrzadzki** [comment]
Second this. The first time I click Obfuscate Module I get this:
Throwable: Icon cannot be found in '/nodes/ModuleClosed.png', aClass='class com.github.intelliguard.ui.JarOptionsForm'

then on subsequent tries:
NoClassDefFoundError: Could not initialize class com.github.intelliguard.ui.JarOptionsForm: Could not initialize class com.github.intelliguard.ui.JarOptionsForm

**Comment by bijeshcj** [comment]
Am getting the same error 

Icon cannot be found in '/nodes/ModuleClosed.png', aClass='class com.github.intelliguard.ui.JarOptionsForm'
java.lang.Throwable

**Comment by patriq** [comment]
Did this plugin stpooed being updated? Im getting this aswell :-1:

**Comment by StellaArtois** [comment]
See https://github.com/olehrgf/intelliguard/tree/IntellijIdea13.1

Thanks to olehrgf, this fork (the IntellijIdea13.1 branch) works on IDEA 14 for me.

Using the above repo, I rebuilt the jar (add plugin.xml to the META-INF, and build adding dependencies from (Intelij install path)/lib), and copied this over the existing intelliguard.jar in the (user home dir)/.ideaC14/config/plugins dir. Seems to work fine.
